### PR TITLE
Backport CA-358583: Fix PROXY metadata to multiple HTTPS requests on a connection

### PR DESCRIPTION
**Pull request by stormi**

### CODE REVIEW

**Review by robhoes — APPROVED** [review]

**Comment by stormi** [comment]
I think there are a few formatting issues due to my conflict-solving (I spotted at least one)

**Comment by stormi** [comment]
The diff should be cleaner now, with less unneeded formatting changes. Let me just check it builds :)

**Review by lindig — APPROVED** [review]

**Comment by stormi** [comment]
It does still build after my formatting changes :+1:

**Review by psafont — COMMENTED** [review]
I've checked locally that it builds, It would be good to have a confirmation that this fixes the issue as expected

**Comment by stormi** [comment]
I had checked it fixes the issue before bringing formatting-only changes, but I'll do another test now.

**Comment by stormi** [comment]
New test results: all good.

**Pull request merged**
