### PR TITLE
update travis to use the new xs-opam

### PR DESCRIPTION
**Pull request by mseri**
This also enables coverage

Signed-off-by: Marcello Seri <marcello.seri@citrix.com>

### CODE REVIEW

**Comment by mseri** [comment]
I have activated the coverage. I am also trying to understand why the tests are not executed outside the coverage run, even though the variable TESTS appear to be true and this is the actual default in https://github.com/ocaml/ocaml-ci-scripts/blob/master/ci_opam.ml#L41 (executed by the travis-ocaml script)

**Comment by gaborigloi** [comment]
It seems that the `_oasis` file does not define any test.

**Comment by mseri** [comment]
Indeed, there are no tests and therefore also coveralls fails. I have updated the travis configuration to avoid running the coverage pointlessly

**Comment by gaborigloi** [comment]
Oh ok, we can then add the tests in a subsequent PR.

**Pull request merged**
