### PR TITLE
Enable Http_test tests and coverage

### PR DESCRIPTION
**Pull request by gaborigloi**
Signed-off-by: Gabor Igloi <gabor.igloi@citrix.com>

### CODE REVIEW

**Comment by gaborigloi** [comment]
For some reason coverage is only reported for 3 files in `http-svr`: https://coveralls.io/builds/12066353

**Comment by mseri** [comment]
Looks like it's the only thing with tests...

**Comment by gaborigloi** [comment]
@mseri Shall I add a coverage badge as well? I didn't add it because it showed a really good percentage, just because we only test this module, so that was a bit misleading.

**Comment by mseri** [comment]
Let's not put it for the moment

**Pull request merged**
