### PR TITLE
CA-368579: Mitigations against DoS attacks by unauthenticated clients (Yangtze)

### PR DESCRIPTION
**Pull request by robhoes**

### CODE REVIEW

**Comment by psafont** [comment]
We should get unit-tests here, all other CI has reported issues

**Comment by lindig** [comment]
This is a backport, I assume?

**Comment by robhoes** [comment]
Yes, see https://github.com/xapi-project/xen-api/pull/4817

**Review by lindig — APPROVED** [review]

**Comment by robhoes** [comment]
@psafont The tests have now been run, and passed.

**Review by psafont — APPROVED** [review]

**Pull request merged**
