### PR TITLE
CP-29015: Set correct ciphers for stunnel client

### PR DESCRIPTION
**Pull request by makunterry**
Signed-off-by: Kun Ma <kun.ma@citrix.com>

### CODE REVIEW

**Comment by cheng-z** [comment]
Hi @jonludlam and @krizex 
Could you please review the code and merge if no concern?
Thanks.

**Comment by cheng-z** [comment]
As the time for master merge close and all test been passed. We will merge the code to master if no other concern. Please shout if any comments.

**Comment by lindig** [comment]
I think this area could be cleaned up a bit with code like this:
* avoid using slow `@` list concat
* make structure more linear like the file it creates

```
  let lines = 
    String.concat "\n" @@ List.concat
    [ [ "client=yes"
      ; "foreground=yes"
      ; "socket = r:TCP_NODELAY=1"
      ; "socket = r:SO_KEEPALIVE=1"
      ; "socket = a:SO_KEEPALIVE=1"
      ; (match !timeoutidle with 
        | None -> "" 
        | Some x -> Printf.sprintf "TIMEOUTidle = %d" x)
      ; Printf.sprintf "connect=%s:%d" host port
      ; "fips = no"; (* stunnel fips-mode stops us using sslVersion other than TLSv1 which means 1.0 only. *)
      ]
    ; if extended_diagnosis then ["debug=4"] else []
    ; if verify_cert then
        ["verify=2"
        ; sprintf "CApath=%s" certificate_path
        ; sprintf "CRLpath=%s" crl_path
        ] 
      else []
    ; if legacy then 
        [ "sslVersion = all"
        ; "options = NO_SSLv2"
        ; "options = NO_SSLv3"
        ; "ciphers = " ^ (good_ciphers ()) ^ (match !legacy_ciphersuites with "" -> "" | s -> (":" ^ s))
        ] 
      else 
        [ "sslVersion = TLSv1.2"
        ; "ciphers = " ^ (good_ciphers ())
        ]
    ]
```

**Comment by cheng-z** [comment]
Thank you all for your comment.
As @makunterry is now on paternity leave. Please @xiewei20082008 rework the comment and create another PR and link to this one.
Also please close this PR and use the new PR to do code merge.

**Comment by xiewei20082008** [comment]
Close this PR please. I raised a new PR here [https://github.com/xapi-project/xen-api-libs-transitional/pull/48]

**Pull request closed without merging**
