### PR TITLE
Use HTTP/1.1 in 101 response

### PR DESCRIPTION
**Pull request by benjamreis**
Solves: https://github.com/xapi-project/wsproxy/issues/24

### CODE REVIEW

**Comment by psafont** [comment]
I think it only makes sense to allow version 1.1: lower it's not possible because of the spec, and the server doesn't support 2.0

**Comment by benjamreis** [comment]
Are there plans to support 2.0? Or should I just hardcode 1.1 as the version? It'd simplify the code for sure but if 2.0 is supported eventually it'd require modifications. What do you prefer?

**Comment by psafont** [comment]
There are no plans to support 2.0, it's not trivial to do and the libraries that shave 2.0 support in ocaml are still experimental. There is an effort needed to switch to those as well, the current implementation is all homegrown.

Hopefully soon with cohttp 4 this can be possible. The is also httpaf with experimental patches. But the xapi stack is already using cohttp for some clients and I think it's worth upgrading to the latest version and trying to make it work here.

**Comment by benjamreis** [comment]
So you want to use cohttp here?

**Comment by benjamreis** [comment]
I've hard coded `1.1` to be able to test and have fix as fast as possible, siicne its broken the sooner, the better.

I don't know cohttp so I need to learn it before implementing it here. This should be done in its own PR IMHO.

**Comment by benjamreis** [comment]
I'm re-reading the spec but I see nothing missing.

**Review by lindig — APPROVED** [review]

**Review by psafont — APPROVED** [review]

**Pull request merged**
