### PR TITLE
CA-336258: http-svr: add JSONRPC_protocol

### PR DESCRIPTION
**Pull request by robhoes**
Backport for Havana.

### CODE REVIEW

**Comment by olivierlambert** [comment]
Hi!

is Havana the code name for XAPI in 7.1 LTS?

**Comment by edwintorok** [comment]
Yes, the codename is apparently missing from http://xapi-project.github.io/xen-api/releases.html

**Comment by robhoes** [comment]
7.1CU2/Havana doesn't appear in the API docs, because there were no API changes.

**Comment by edwintorok** [comment]
http://xapi-project.github.io/xen-api/releases/honolulu.html is in a similar situation and is there though.

**Pull request merged**
